### ISSUE TITLE
The  _set_sysmeta method writes wrong CID into file

### ISSUE THREAD

**Issue by taojing2002** [DataONEorg/hashstore#1]
The  _set_sysmeta method writes the CID of the PID itself into the system metadata file. Actually, the CID of the data object  should be written into the file.
So we may modify the method to:
```
def _set_sysmeta(self, pid, sysmeta, obj_cid):
```

**Comment by mbjones** [comment]
@doulikecookiedough Fixed this in sha [2e91dfb](https://github.com/DataONEorg/hashstore/commit/2e91dfb732e158904ba63a159b929121478c0379) by adding a new argument for the systemmetadata cid.

**Comment by doulikecookiedough** [comment]
Thank you for updating this issue Matt - closing issue as bug has been resolved.
