### ISSUE TITLE
Add standard logging module and clean up docstrings

### ISSUE THREAD

**Issue by doulikecookiedough** [DataONEorg/hashstore#10]
Discuss what type of events we want to keep track of

**Comment by mbjones** [comment]
Quick proposal for discussion:

At ERRORS and WARNINGS levels:

- any thrown exceptions or error conditions, at the appropriate severity level

At INFO level:

- a single message for each public API call structured to show success or failure (e.g. "Successfully stored hash: XXYYZX" or "Failed to store PID: doi:XXXX/677y87867"  -- these are off the cuff examples and may not sync with the API fully, so don't take them literally

At DEBUG level: 

- Detailed progress messages for each API call, showing movement through the process (e.g., at start and end of each implementation method, and exposing key data for debugging. For some simpler methods, this may not be needed

**Comment by doulikecookiedough** [comment]
Additionally, review doc strings and ensure they are all consistently formatted (periods, capitalization, etc.)

**Comment by doulikecookiedough** [comment]
Doc strings have been reviewed for consistency of usage of punctuation in [PR-30: Refactor HashStore to enhance modularity and configurability](https://github.com/DataONEorg/hashstore/pull/30).

**Comment by doulikecookiedough** [comment]
Standard logging module has been added in branch 'feature-10-standard-logging'. Logging statements have been written for the initialization process. However, I had to include a questionable parameter to `logging.basicConfig(force=True,...)` to get logging to write into the desired file as expected.

The rest of the logging statements need to be written, but am currently investigating the usage of `force=True` to ensure that this is the best way to have resolved my issue.

**Comment by doulikecookiedough** [comment]
It appears that allowing the python logging module determine where the log file is written is standard practice. However, I would like to place logs at the store root because I feel that it would be less confusing to look there; since the default location may be shared with other logs potentially (ex. access logs, error logs, etc.). I will confirm in our backend discussion, and continue to add logging statements to  the 'FileHashStore' class in the meantime.

**Comment by mbjones** [comment]
> It appears that allowing the python logging module determine where the log file is written is standard practice

Let's chat tomorrow, but I think it is best practice to not override incoming log preferences from the deployment. And logging config is very deployment-specific -- e.g., the differences between deploying in a VM with filesystem access, versus in a K8S container with a logging facility (see https://kubernetes.io/docs/concepts/cluster-administration/logging/).

**Comment by doulikecookiedough** [comment]
I have removed the logging configuration as we discussed and have added logging statements to the `FileHashStore` module. Changes have been merged into develop via pull request [Feature-10: Standard Logging](https://github.com/DataONEorg/hashstore/pull/33).
