### ISSUE TITLE
Add script entry point in pyproject.toml

### ISSUE THREAD

**Issue by datadavev** [DataONEorg/hashstore#135]
Suggest adding the cli entry point in `pyptoject.toml` to facilitate command line use[^1]. A user may then pip or poetry install and run the client directly. e.g.:

```
[tool.poetry.scripts]
hashstore = 'hashstore.client:main'
```

[^1]: https://python-poetry.org/docs/pyproject/#scripts

**Comment by doulikecookiedough** [comment]
Closing this ticket as it has been resolved via [Feature-92: HashStore Client Syntax](https://github.com/DataONEorg/hashstore/pull/104) which has been merged into `develop`
