### ISSUE TITLE
Add version info to hashstore lib

### ISSUE THREAD

**Issue by datadavev** [DataONEorg/hashstore#136]
Version is available in the `pyproject.toml` but not in code.

Suggest adding `__version__ = '1.0.0'` to `hashstore/__init__.py` and managing version info using poetry, and report the version number in the cli. 

e.g. add to `pyproject.toml`:

```
[tool.poetry_bumpversion.file."src/hashstore/__init__.py"]
```

Then install [bump_version](https://pypi.org/project/poetry-bumpversion/) in your local poetry environment and manage versions like:

```
$ poetry version patch
```
To update the patch etc release number.

**Comment by doulikecookiedough** [comment]
This has been completed via the following commits in `feature-133-release-prep` which will be merged into `develop`:
- [Add poetry bump version code to 'pyproject.toml'](https://github.com/DataONEorg/hashstore/commit/22624db56d237c69043e6d60b621a20c5aec46b8)
- [Update version to '1.1.0' via 'poetry version minor'](https://github.com/DataONEorg/hashstore/commit/50b8f8d044fc463b568e6288e6bfe7d6b867f9d5)
