### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by datadavev** [DataONEorg/hashstore#137]
Suggest adding [type hints](https://peps.python.org/pep-0484/) to the code to facilitate rapid development and reduce confusion over variable types (especially useful in method signatures).

**Comment by doulikecookiedough** [comment]
This has been completed via [Add type hints to all method signatures, fix minor issues related to …](https://github.com/DataONEorg/hashstore/commit/44b1f79675fa75f876b8cdc310235a337528cd55)
