### ISSUE TITLE
Use a lib for constructing yaml

### ISSUE THREAD

**Issue by datadavev** [DataONEorg/hashstore#138]
https://github.com/DataONEorg/hashstore/blob/294b4fe9168edb7fa9f44fe9d285bf4be4f33f01/src/hashstore/filehashstore.py#L226

YAML has a [number of gotchas](https://ruudvanasseldonk.com/2023/01/11/the-yaml-document-from-hell) that can cause surprising behavior. Suggest creating YAML using a library instead of building from a formatted string.

**Comment by doulikecookiedough** [comment]
This has been completed via [Feature-139: Path Construction & Clean Up](https://github.com/DataONEorg/hashstore/pull/143)

**Comment by doulikecookiedough** [comment]
Thank you for this suggestion @datadavev! This has been completed via [Feature-138: Construct HashStore Config Yaml with Library](https://github.com/DataONEorg/hashstore/pull/144)

The key-value pair content is now built through `yaml.dump(...)` and combined with the comments section to form the contents of the `hashstore.yaml` file.
