### ISSUE TITLE
Use path libs for constructing paths

### ISSUE THREAD

**Issue by datadavev** [DataONEorg/hashstore#139]
https://github.com/DataONEorg/hashstore/blob/294b4fe9168edb7fa9f44fe9d285bf4be4f33f01/src/hashstore/client.py#L750

Scattered throughout the code is a mix of format strings, string concatenation, and pathlib mechanisms used for constructing file path. Suggest just using [pathlib](https://docs.python.org/3/library/pathlib.html) or at least using `os.path.join()` for constructing paths.

**Comment by doulikecookiedough** [comment]
This has been completed via [Feature-139: Path Construction & Clean Up](https://github.com/DataONEorg/hashstore/pull/143)

Note - Accidentally replied to wrong ticket.
