### ISSUE TITLE
Use module name in logging

### ISSUE THREAD

**Issue by datadavev** [DataONEorg/hashstore#140]
https://github.com/DataONEorg/hashstore/blob/294b4fe9168edb7fa9f44fe9d285bf4be4f33f01/src/hashstore/filehashstore.py#L87

Logging using the module name can assist with clear logging by labeling messages with module name and providing the ability to set log level per module (helpful for downstream users). Suggest using something like:

```
def getLogger():
    return logging.getLogger(__name__)
```

Then using `getLogger()` within the code to get a logger instance per class or when needed. e.g.:

```
def foo():
    L = getLogger()
    L.debug("foo message")
```

**Comment by doulikecookiedough** [comment]
This has been completed via [Feature-140: Logging Enhancement](https://github.com/DataONEorg/hashstore/pull/145)
