### ISSUE TITLE
Create mermaid diagrams to discuss object deduplication flow

### ISSUE THREAD

**Issue by doulikecookiedough** [DataONEorg/hashstore#15]
Leave mermaid syntax here for reference and upload photos/update documentation in [storage-subsystem.rst](https://github.com/NCEAS/metacat/edit/feature-1436-storage-and-indexing/docs/user/metacat/source/storage-subsystem.rst)

**Comment by doulikecookiedough** [comment]
Proposed **store_object** flow
![hashstore_store_object](https://user-images.githubusercontent.com/12792837/230479820-50c1b283-f87c-4948-a3f5-304da67db862.png)
```
sequenceDiagram
    Metacat->>+HashStore: store_object(data)
    HashStore->>+HashFS: add_object(data)
    HashFS->>+FS(../metacat/objects): put(data), write to tmpFile
        Note right of FS(../metacat/objects): (object) tmpFile
    alt is duplicate
        HashFS->>HashFS: tmpFile.delete(), is_duplicate = true
    rect rgb(255, 0, 0, 0.1)
        HashFS-->>HashStore: is_duplicate = true
        HashStore-->>Metacat: is_duplicate = true
    end
    else is not duplicate
        HashFS->>+FS(../metacat/objects): move(tmpFile) -> (permanent addresss)
        Note right of FS(../metacat/objects): (object) 4d/19/81/71eef969d553d4c...bc014c05972c
        HashFS->>+FS(../metacat/objects): if .txt/.log/TBD does not exist (obj comes first),  create it
        Note right of FS(../metacat/objects): (empty file) 4d/19/81/71eef969d553d4c...bc014c05972c.txt
        rect rgb(2, 255, 0, 0.1)
        HashFS-->>+HashStore: hex_digests("md5": "...", "sha256": "...")
        HashStore-->>+Metacat: hex_digests("md5": "...", "sha256": "...")
        end
    end
```

**Comment by mbjones** [comment]
Thanks @doulikecookiedough, this looks great. Very helpful. Let's discuss the points below. I think we could make a few improvements, such as:

1) be sure to indicate the return paths and values so we can follow the control path
    - for example, where does HashFS.putData() return? I suspect it returns to the addData() method (see example below)
2) I think the final column for `FS` is not really an object in the system, as it isn't a code module -- I think it should be eliminated (again, see example below)
3) please indicate activation streams when each function is active
4) it's unclear to me what is happening in the `is_not_duplicate` block with the `move` and `if` arrows. Are they both function calls? Where do they return?  Generally conditional logic would be in an alt block, not in text of an arrow representing a method call. 
5) Why is a file created with a `.txt` extension? I don't remember this in our spec, but I might be forgetting it. 
6) when `store()` returns in the duplicate==true case, shouldn't it still return the checksum array? And same with `add_object()`?

I gave some examples of (1) and (2) in the diagram below, but I wasn't sure how to deal with (4) and (5)

```mermaid
sequenceDiagram
    Metacat->>+HashStore: store_object(data)
    HashStore->>+HashFS: add_object(data)
    HashFS->>+HashFS: put(data)
        Note right of HashFS: (object) tmpFile
    alt is duplicate
        HashFS->>HashFS: tmpFile.delete(), is_duplicate = true
    rect rgb(255, 0, 0, 0.1)
        HashFS-->>HashStore: is_duplicate = true
        HashStore-->>Metacat: is_duplicate = true
    end
    else is not duplicate
        HashFS->>+HashFS: move(tmpFile) -> (permanent addresss)
        Note right of HashFS: (object) 4d/19/81/71eef969d553d4c...bc014c05972c
        HashFS->>+HashFS: if .txt/.log/TBD does not exist (obj comes first),  create it
        Note right of HashFS: (empty file) 4d/19/81/71eef969d553d4c...bc014c05972c.txt
        rect rgb(2, 255, 0, 0.1)
        HashFS-->>+HashStore: hex_digests("md5": "...", "sha256": "...")
        HashStore-->>+Metacat: hex_digests("md5": "...", "sha256": "...")
        end
    end
```

**Comment by doulikecookiedough** [comment]
Thank you for the feedback/direction @mbjones. I'll make sure the `store_sysmeta` diagram is appropriately created and you can find the updated `store_object` diagram and my responses below:
1. `put` calls `_copy` which returns hex-digests, filepath and is_duplicate. 
2. Understood - and removed that Actor
3. Added activation streams.
4. I updated the text and rectangles - at this point HashFSExt is returning values.
5. In our call, we did not finalize the details of what this deduplication file would be/look like. I put down a .txt file because I thought it would be easy to open/read/write without any additional libraries/parsers, but this (and the details of what exactly the contents will be) is completely up for discussion.
 - Also, should this deduplication file be created for every object stored? That would be a lot of extra objects, which should be fine but doesn't leave a good feeling with me at this time of writing. Or should it only be created when is_duplicate == true, and when Metacat attempts to store sysmeta? I will bring this up during our next Arc Dev meeting.
6. Yes it should return the checksum array when is_duplicate == true - sorry for the lack of clarity. I added details to the diagram which should clarify the current process. In the is_duplicate == false scenario, it follows up by raising an error. 

```mermaid
sequenceDiagram
    Metacat->>HashStore: store_object(data, algorithm, checksum)
    activate HashStore
    HashStore->>HashFSExt: add_object(data, algorithm, checksum)
    deactivate HashStore
    activate HashFSExt
    HashFSExt->>HashFSExt: put(data, algorithm, checksum)
    HashFSExt->>HashFSExt: _copy(data, algorithm, checksum)
    HashFSExt->>HashFSExt: _mktempfile(stream)
    Note right of HashFSExt: (object) tmpFile
    HashFSExt-->>HashFSExt: return (hex_digests, filepath, is_duplicate)
    deactivate HashFSExt
    alt is_duplicate = true
        activate HashFSExt
        HashFSExt->>HashFSExt: tmpFile.delete()
        deactivate HashFSExt
    rect rgb(255, 0, 0, 0.1)
        HashFSExt-->>HashStore: return HashAddress(id, self.relpath(filepath), filepath, is_duplicate, hex_digest_dict)
        HashStore-->>HashStore: raise FileExistsError("...")
    end
    else is_duplicate = false
        activate HashFSExt
        HashFSExt->>HashFSExt: move(tmpFile) -> (permanent addresss)
        Note right of HashFSExt: (object) 4d/19/81/71eef969d553d4c...bc014c05972c
        HashFSExt->>HashFSExt: DISCUSS: if .txt/.log/TBD does not exist (obj comes first),  create it
        deactivate HashFSExt
        Note right of HashFSExt: (empty file) 4d/19/81/71eef969d553d4c...bc014c05972c.txt
        rect rgb(2, 255, 0, 0.1)
        HashFSExt-->>HashStore: return HashAddress(id, self.relpath(filepath), filepath, is_duplicate, hex_digest_dict)
        end
        HashStore-->>Metacat: return hex_digests (ex. "md5": "...", "sha256": "...")
    end
```

**Comment by doulikecookiedough** [comment]
This is the current flow for `store_sysmeta`. After putting this together and trying to add in the deduplication process (creating and writing into the deduplication file), it feels like the process should not exist in either `store_object` or `store_sysmeta` - but should be handled by Metacat with a new HashStore method (`update_dedupe_scids` ?) that is called at the end of the storage process.
  - **update_dedupe_scids(action, address, s_cid)**
    - If `action` is "add":
       - If no deduplication file, create one
          - write `s_cid` to the `address`.tmp (exact format tbd, split by a delimiter I would assume, that we can read and work with in an array)
    - If `action` is "delete":
       - Read deduplication file, remove "s_cid"
```mermaid
sequenceDiagram
    Metacat->>+HashStore: store_sysmeta(pid, sysmeta, cid)
    Note over HashStore: Add locked_pids[pid]
    HashStore->>-HashStore: _set_sysmeta(pid, sysmeta, cid)
    HashStore->>+HashFSExt: sysmeta.exists(s_cid)
    HashFSExt-->-HashStore: return boolean
    alt s_cid == true
        HashStore->>+HashStore: Rename existing s_cid -> s_cid.tmp
        HashStore->>HashStore: Write to empty "s_cid" object
        HashStore->>HashStore: Delete "s_cid".tmp
        Note over HashStore: Release locked_pids[pid]
        rect rgb(2, 255, 0, 0.1) 
        HashStore-->>-Metacat: return sysmeta_cid
        end
    else s_cid == false
        HashStore->>+HashStore: Write to empty "s_cid" object
        Note over HashStore: Release locked_pids[pid]
        rect rgb(2, 255, 0, 0.1) 
        HashStore-->>-Metacat: return sysmeta_cid
        end
    else Exception
        Note right of HashStore: Abort Process / Rollback
        HashStore->>+HashFSExt: sysmeta.exists(s_cid.tmp)
        HashFSExt-->>-HashStore: return boolean
        HashStore->>+HashFSExt: sysmeta.exists(s_cid)
        HashFSExt-->>-HashStore: return boolean
        HashStore->>+HashStore: Delete s_cid
        HashStore->>+HashStore: Rename s_cid.tmp -> s_cid
        rect rgb(255, 0, 0, 0.1) 
        HashStore-->>-Metacat: Raise Error
        end
    end
```

**Comment by doulikecookiedough** [comment]
After further discussion, we have decided to proceed with using the pid hash as the key for objects (same as the sysmeta) to reduce the complexity of the `store_object` process. We will still return the hex digest dictionary for Metacat to handle and keep track of, but files will be stored using the pid hash instead of the content hash. Another advantage of using the pid hash will be the ability to check for a duplicate object before the transfer process begins. Details and rationale can be found in the [storage-subsystem document](https://github.com/NCEAS/metacat/blob/feature-1436-storage-and-indexing/docs/user/metacat/source/storage-subsystem.rst)

The updated `store_object` process is as follows:
```mermaid
sequenceDiagram
    Metacat->>+HashStore: store_object(data, algorithm, checksum)
    HashStore->>-HashFSExt: add_object(data, algorithm, checksum)
    HashFSExt->>+HashFSExt: put(data, algorithm, checksum)
    HashFSExt->>HashFSExt: _move_and_get_checksums(data, algorithm, checksum)
    HashFSExt->>HashFSExt: _mktempfile(stream)
    Note right of HashFSExt: (object) tmpFile
    HashFSExt-->>-HashFSExt: return (hex_digests, filepath, is_duplicate)
    alt is_duplicate = true
        HashFSExt->>+HashFSExt: put(): tmpFile.delete()
    rect rgb(255, 0, 0, 0.1)
        HashFSExt-->>-HashStore: return HashAddress(id, self.relpath(filepath), filepath, is_duplicate, hex_digest_dict)
    end
        HashStore-->>Metacat: return HashAddress(id, self.relpath(filepath), filepath, is_duplicate, hex_digest_dict)
    else is_duplicate = false
        HashFSExt->>+HashFSExt: put(): move(tmpFile) -> (permanent addresss)
        Note right of HashFSExt: (object) 4d/19/81/71eef969d553d4c...bc014c05972c
        rect rgb(2, 255, 0, 0.1)
        HashFSExt-->>-HashStore: return HashAddress(id, self.relpath(filepath), filepath, is_duplicate, hex_digest_dict)
        end
        HashStore-->>Metacat: return HashAddress(id, self.relpath(filepath), filepath, is_duplicate, hex_digest_dict)
    end
```

**Comment by doulikecookiedough** [comment]
These mermaid diagrams will be added to the storage subsystem document once the flow has been reviewed via other issues.
