### ISSUE TITLE
Refactor HashStore configuration and initialization process

### ISSUE THREAD

**Issue by doulikecookiedough** [DataONEorg/hashstore#29]
Prevent clients from modifying an initialized `HashStore` with different depths or widths:
- Currently, there is a risk of clients unintentionally (or intentionally) modifying the configuration of an initialized `HashStore`, specifically the depth and width parameters. This can lead to data integrity issues and unexpected behaviour. We need to implement a mechanism to enforce the configuration of `HashStore` instances. This enhancement is crucial before proceeding with a production release.

**Potential Solution:**
To address this issue, we could create a metadata file that stores the configuration data for each `HashStore` instance. This metadata file would include essential information such as the hash algorithm, width, depth, root directory, and other relevant settings (tbd).
- To Discuss: Before allowing any modifications or operations on a `HashStore`, should we validate the configuration data against the metadata file to ensure consistency?

Note: The specific implementation details of the metadata file and validation process can/will be discussed further during Arc Dev sessions.

**Comment by mbjones** [comment]
In addition to depth and width, we also need to be sure the checksum algorithm doesn't change. Even if we have a metadata file, I think a quick check of the directory structure is also useful to verify the on-disk layout conforms to the metadata and the request.

**Comment by doulikecookiedough** [comment]
`FileHashStore` now initializes based on a properties dictionary, which must be supplied when the factory method for HashStore is called. This initialization process will be reviewed after the Java implementation of the equivalent is implemented.
