### ISSUE TITLE
Determine depth level for directories

### ISSUE THREAD

**Issue by doulikecookiedough** [DataONEorg/hashstore#3]
Discuss the implications of having exponentially large dataset submissions over time - and how that will affect our proposed hashstore solution at its current depth.

We may need to increase the depth level to ensure that our solution accounts for future submissions that may exceed what is estimated.

**Comment by mbjones** [comment]
From the [Physical Layout design doc](https://github.com/NCEAS/metacat/blob/feature-1436-storage-and-indexing/docs/user/metacat/source/storage-subsystem.rst#physical-file-layout):

> Because each digit in the hash can contain 16 values, the directory structure can contain 65,536 subdirectories (256^2).

If we move to 3 levels, we get 256^3 directories == 16,777,216 ~ 16M -- so a big jump. So the main discussion is whether 65K or 16M directories is better for organizing our content. How many files do we have now and expect in the future, and, assuming they are fairly evenly distributed across, how many files per directory would we expect?

**Comment by doulikecookiedough** [comment]
**Context:**

If we follow the existing growth rate of ~ 12TB and 1 million objects per year, over 10 years that would be 10 million objects and ~ 120TB of data. **Assuming an even distribution of objects:**
- If there were 65K directories, there would be **~153** objects per directory
- If there were 16M directories, there would be **~0.625** objects per directory

If we use an aggressive estimate of ~60TB and 5 million objects per year per year, over 10 years that would be 50 million objects and ~600TB of data.
- If there were 65K directories, there would be **~769** objects per directory
- If there were 16M directories, there would be **~3.125** objects per directory

**Findings & Rationale:**
- Using the aggressive estimate with 65K directories, it's not that unreasonable to have 769 files in a directory potentially. However, there is an online consensus that having many files in one folder is not a good practice in general - and there are more recommendations for having as few files as possibles per directory.
-- On CephFS's documentation, they also agree that it's not a [best practice](https://docs.ceph.com/en/latest/cephfs/app-best-practices) to do so (the example used is 1 million files in a directory).
- There does not appear to be a directory limit for more recent file systems like XFS (user responded that he was able to reach [16 million directories](https://www.linuxquestions.org/questions/linux-newbie-8/maximum-number-of-directories-under-xfs-647200/)) or any mention of a directory limit in CephFS either.
-- Given our current proposed implementation where files are retrieved based on PIDs provided (the direct path to obj), we should not have performance issues when retrieving files even if they're stored several levels deep.
- While you can technically fit many files in a directory in modern filesystems, it will eventually lead to performance issues for common operations as file grows, like when attempting to get a list of files in the directory itself.
- Links of interest:
-- [CephFS discussion RE: maximum number of files per directory](https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/2BT2F7JFGGAIPR4VUOUFENKRZ6HN7OZG/)
-- [NFTS Performance and Large Volumes](https://stackoverflow.com/questions/197162/ntfs-performance-and-large-volumes-of-files-and-directories)
-- [Discussion on # of folders in a Windows Folder](https://superuser.com/questions/1624192/how-many-folders-can-i-put-in-one-windows-folder)
-- [Performance discussion of retrieving files via web](https://serverfault.com/questions/98235/how-many-files-in-a-directory-is-too-many-downloading-data-from-net#:~:text=My%20general%20rule%20of%20thumb,start%20having%20serious%20performance%20issues.)
- Assuming that we want to future-proof our substorage system and not have another re-factor down the line, we should prepare to receive escalating large datasets in terms of TB and objects.
-- If we double our aggressive estimate (10 million objects per year), we will still potentially have a very reasonable amount of files per directory with 16M directories
---- If there were 65K directories, there would be **~1538** objects per directory
---- If there were 16M directories, there would be **~6.25** objects per directory


**Recommended Directory Levels:**
- 3 Levels, 16M directories

**Next Steps:**
- Review with Matt and discuss whether findings and/or if this needs to be benchmarked (and how to if so) for approval

**Comment by doulikecookiedough** [comment]
After discussing with the team, we have agreed to proceed with 3 directory levels deep.
