### ISSUE TITLE
Extensively Test HashStore for 1.1.0

### ISSUE THREAD

**Issue by doulikecookiedough** [DataONEorg/hashstore#32]
To prepare for production release 1.0.0, we need to ensure that our Public API methods have been tested extensively, especially with regards to the object and sysmeta locks.

**To Do:**
- Test with real datasets
- Explore multiple instances of HashStore attempting to store the same duplicate objects and sysmeta concurrently
- Consider other race conditions and add new pytests where applicable

**Comment by doulikecookiedough** [comment]
**Update:**
- Stored all objects from `var/metacat/data` in `knbvm` (test.arcticdata.io) to a HashStore: `/home/mok/testing/knbvm_hashstore` via Python Client app.
    - Overview:
        - Total Objects Possible to Convert: 585371
        - Total Objects Stored: 582898
        - Objects unaccounted for (no pids found): 2473
    - Retrieved objects via Java Client app:
        - 579770 checksums match
        - 3128 do not match, it appears that the checksums stored are incorrect
- Stored all metadata from `var/metacat/documents` in `knbvm` (test.arcticdata.io) to a HashStore: `/home/mok/testing/knbvm_hashstore` via Python Client app.
    - Overview:
        - Total Metadata Possible to Convert: 34915
        - Total Metadata Stored: 34915
- Storage/retrieval based on values obtained by accessing the `identifier` and `systemmetadata` tables in metacat postgres db

**Comment by doulikecookiedough** [comment]
**Update:**
- Using values obtained by querying metacat postgres db:
   - Stored list of objects (~580k) via Java and retrieved with Python
   - Stored list of objects (~580k) via Python and retrieved with Java
   - Deleted list of objects via Python
   - Stored, retrieved and deleted list of metadata via Python

**Next Up:**
- Test for sensible responses when attempting to store the same pid with asynchronous parallel writes
- Test deleting objects via Java
- Test re-storing, retrieving and deleting metadata via Java

**Comment by doulikecookiedough** [comment]
**Summary/Update:**
- Tested deleting objects via Java
- Tested storing, retrieving and deleting metadata via Java & Python
- Confirming that we can store, retrieve and delete objects using both Java and Python interchangeably. 
    - The testing process uncovered a few latent bugs (that were fixed) and provided peace of mind that the code base is robust. There were no exceptions encountered that I didn't expect to see.
    - Storing data objects via the metacat db with both Java/Python produced the same number of files stored (and not stored due to the same reason, which was that the checksum found in the db does not match what has been calculated). The mismatch is not due to a calculation error, but likely an input error from test data in `knbvm`. 
    - Data objects were also retrieved and validated (calculating the checksum from the stream and comparing against the db). Data objects were also all deleted as expected. 
    - Storing metadata via the metacat db with both Java/Python produced the same number of metadata documents stored. Metadata objects were retrieved, validated and deleted without any concerns.

**Up Next:**
- Create race conditions to test the locking (and not storing duplicates unintentionally). I will report back here with my logic for review with the backend team.

**Comment by doulikecookiedough** [comment]
Testing Strategy for Review #1:

**Python:**
- Multiprocessing Library Test
    - Using multiprocessing, I can create separate processes that do not have any shared resources/variables. 
    - This type of test means that the pid lock would be ineffective and all processes created would attempt to store the same object.
    - **Race Condition:** Multiple processes all attempting to store different objects but with the same pid:
        - Multiprocessing.pool() receives a list with 20 integers, either 1 or 2. A maximum of 10 processes execute at any one time.
        - This list gets unpacked as individual arguments and are passed into a method which will either call `store_object` on a large file (5GB) or smaller file (500MB) based on the integer with the same pid. 
        - Since the pid lock is bypassed due to separate memory space from using processes, one process will be the first to create a (large/small) temporary file and attempt to move it to its final location.
        - **Results:**
             - All 10 processes immediately begin to create a temporary file after moving past the pid lock
             - One process completes before the other for the smaller tmp file (500MB), and moves the file to its permanent location
             - The processes creating the smaller tmp file (500mb) that finish creating their temporary file after detects that the object already exists at the permanent location, and deletes its respective temporary file.
             - The processes that get spawned afterwards after the pool opens up can see that a file already exists, and exits immediately.
             - The processes that finish creating their temporary file late (because they are copying a large file (5GB)), see that a file already exists, and deletes its respective temporary file.
         - **Conlusion:**
            - The behaviour seems reasonable, and the results are reproducible. When the list provided to store triggers the same size, the same behaviour is seen.
            - Objects should always be stored with a checksum and checksum algorithm to be completely sure that the correct file is stored.

```
Storing 1 type object. 1 = 5GB, 2 = 500MB
Storing 1 type object. 1 = 5GB, 2 = 500MB
Storing 2 type object. 1 = 5GB, 2 = 500MB
Storing 2 type object. 1 = 5GB, 2 = 500MB
Storing 1 type object. 1 = 5GB, 2 = 500MB
Storing 2 type object. 1 = 5GB, 2 = 500MB
Storing 1 type object. 1 = 5GB, 2 = 500MB
Storing 2 type object. 1 = 5GB, 2 = 500MB
Storing 1 type object. 1 = 5GB, 2 = 500MB
Storing 2 type object. 1 = 5GB, 2 = 500MB
Storing 1 type object. 1 = 5GB, 2 = 500MB
ERROR:root:FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Storing 2 type object. 1 = 5GB, 2 = 500MB
WARNING:root:FileHashStore - _move_and_get_checksums: Object exists at: /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b, deleting temporary file.
Storing 1 type object. 1 = 5GB, 2 = 500MB
ERROR:root:FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Storing 2 type object. 1 = 5GB, 2 = 500MB
WARNING:root:FileHashStore - _move_and_get_checksums: Object exists at: /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b, deleting temporary file.
Storing 1 type object. 1 = 5GB, 2 = 500MB
ERROR:root:FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Storing 2 type object. 1 = 5GB, 2 = 500MB
WARNING:root:FileHashStore - _move_and_get_checksums: Object exists at: /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b, deleting temporary file.
Storing 1 type object. 1 = 5GB, 2 = 500MB
ERROR:root:FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Storing 2 type object. 1 = 5GB, 2 = 500MB
WARNING:root:FileHashStore - _move_and_get_checksums: Object exists at: /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b, deleting temporary file.
Storing 1 type object. 1 = 5GB, 2 = 500MB
ERROR:root:FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Storing 2 type object. 1 = 5GB, 2 = 500MB
ERROR:root:FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
ERROR:root:FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
ERROR:root:FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
ERROR:root:FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
ERROR:root:FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
WARNING:root:FileHashStore - _move_and_get_checksums: Object exists at: /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b, deleting temporary file.
WARNING:root:FileHashStore - _move_and_get_checksums: Object exists at: /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b, deleting temporary file.
WARNING:root:FileHashStore - _move_and_get_checksums: Object exists at: /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b, deleting temporary file.
WARNING:root:FileHashStore - _move_and_get_checksums: Object exists at: /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b, deleting temporary file.
WARNING:root:FileHashStore - _move_and_get_checksums: Object exists at: /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b, deleting temporary file.
```

**Comment by doulikecookiedough** [comment]
Testing Strategy for Review 2:

**Python:**
- Threading Library Test
    - With threads, resources are shared so creating multiple threads will interact with the pid lock as expected.
    - **Race Condition:** Multiple threads all attempting to store the same object with the same pid
        - Using a loop, I create 20 threads that all call `store_object` on a large file (5GB)
        - Once the first thread is executed, the pid is locked and all threads must wait
            - Only one temporary file is generated, and once completed, is moved to its permanent address
        - The pid is released, and every other thread sees that there is already a file for the given pid and raises a `FileExistsError` exception.
        - **Results:**
            - The pid lock behaves as I expect it to, and I can confirm that they are queued up as there is only one tmp file generated in the `/tmp` folder while it serializes the data.
            - Increasing the number of threads produces the same results. Testing with a 500MB file and the same pid also behaves as I expect it to.

```
Thread 0 Started
Exception in thread Thread-1:
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 1 Started
Exception in thread Thread-2:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 2 Started
Exception in thread Thread-3:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 3 Started
Exception in thread Thread-4:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 4 Started
Exception in thread Thread-5:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 5 Started
Exception in thread Thread-6:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 6 Started
Exception in thread Thread-7:
Traceback (most recent call last):
 ...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 7 Started
Exception in thread Thread-8:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 8 Started
Exception in thread Thread-9:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 9 Started
Exception in thread Thread-10:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 10 Started
Exception in thread Thread-11:
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 11 Started
Exception in thread Thread-12:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 12 Started
Exception in thread Thread-13:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 13 Started
Exception in thread Thread-14:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 14 Started
Exception in thread Thread-15:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 15 Started
Exception in thread Thread-16:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 16 Started
Exception in thread Thread-17:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 17 Started
Exception in thread Thread-18:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 18 Started
Exception in thread Thread-19:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
Thread 19 Started
Exception in thread Thread-20:
Traceback (most recent call last):
...
FileExistsError: FileHashStore - _move_and_get_checksums: File already exists for pid: doutest1 at /Users/doumok/Code/hashstore/douhs/objects/29/25/40/b0f6f28d760c2660f3ac580911504eb6e06d3ef104d323e148b117595b
```
 
 Testing Strategy for Review 3:

**Python:**
- Multiprocessing with threading test
    - Race Condition: Simulate a scenario where multiple processes (separate memory, no shared resources) attempts to store the same pid but different objects with multiple threads (shared resources)
        - 5 processes that each calls store object 10 times via threading, storing both large (5GB) and small (500MB) data file
        - The first process to store the object successfully is the 500MB file, and causes all remaining threads to raise the appropriate `FileExistsError` exception
        - The other 4 processes attempting to store the small object delete their temporary file and raises `FileExistsError` exception on every thread
        - The remaining 5 processes attempting to store the large object once completing the creation of the tmp file see that there is already a file at the permanent address. They delete their respective tmp files, and the remaining threads raise `FileExistsError` exceptions as expected. 
         - **Results:**
             - The expected exception is raised each time, and the pid lock does not throw any unexpected errors.
             - The behaviour is reproducible with an increased amount of processes and threads.
             
 **Conclusion:**
- HashStore (python) appears to be working as expected, and throws `FileExistsError` exception at every point.
- The pid lock for threading behaves as expected, and blocks other threads while `store_object` is executing.
- If there are no shared resources, the first process that moves its file to the permanent address blocks all others - so it's important to store files with their checksums to be 100% safe that the correct file is stored.

**Comment by doulikecookiedough** [comment]
**Testing Update:**
- **Strategy 1 Follow-up:** What happens when we store large files with duplicate pids and different sizes?
    - Objects stored are validated and not being overwritten
    - Exceptions raised are for the correct reason (object already exists) and the temporary files are deleted.
    - Other processes are able to move forward to store their respective objects
    - Cancelling store_object causes `tmp` files generated in `objects/tmp` that have not finished to remain in an incomplete state (and would need to be deleted manually)
- **Strategy 2 Follow-up:** What happens to other threads while a pid is locked? Are they able to move forward with storing?
    - Pids that are not being stored are able to move past the pid lock
    - Objects are validated and stored, and the expected exception is raised for a duplicate object
    - The original test was not actually very accurate (threads created through a for loop), so the test was amended to manually `start()` and `join()` threads that call store_object.
        - Manually increasing the number of Threads also resulted in sensible responses
    - Cancelling midway through the process left temporary files in an incomplete state
- **Strategy 3 Follow-up:** Store lots of different pids with multiprocessing and threading
    - Up to 10 processes were created to call the threading test method which manually started/joined threads (which stored 4 different files: 500MB, 1GB, 3GB, 3.5GB, using the same pids for each respective file)
    - Once files were completed, validated and moved to their final destination, the remaining threads exited as expected and `tmp` files created were all deleted as expected.
- **Strategy 4 Follow-up:** Open multiple terminals to simulate the same results from the combined multiprocessing/threading test in Python but with Java
    - The pid synchronization to store the same objects appears to be working as expected
    - `store_object` is called with a checksum and a checksum algorithm, and the object that I expect to be stored is stored.
    - Exceptions are raised, multiple temporary files are all created and deleted when the JVM sees that an object already exists at the target location
    - Objects with different pids are able to move forward while the rest are in progress.
    - Staggering the commands does not cause any unexpected issues
- **Strategy 5:** Test deleting objects, what happens when we cancel the command halfway through?
    - Python:
        - A multiprocessing pool is created, which is fed a list of different and repeated pids of different sizes and calls `delete_object` on each item in the list
        - When the file or parent folders no longer exists, the expected exception is raised.
        - Cancelling right after executing the command (to interrupt the deletion process) is proving to be difficult, the deletion happens almost instantly. I think it's safe to say that `delete_object` is working as expected.
    - Java:
        - Similarly, a list of repeated pids of different sizes are called upon by `.parallelStream()` to delete and cancelling right after is also proving to be difficult. 
        - Executing the command on multiple terminals is also producing sensible responses (file does not exist). I think it is also safe to say that `deleteObject` in Java is also working as expected.

**Comment by mbjones** [comment]
That all sounds awesome, @doulikecookiedough !

**Comment by mbjones** [comment]
> Cancelling midway through the process left temporary files in an incomplete state

Is there anything we can do about this?

**Comment by doulikecookiedough** [comment]
@mbjones What do you think about using the last modified date to determine whether a tmp file is in progress or not? So as a last step during the instantiation/initialization of a HashStore, we will get the list of blobs in the `/objects/tmp` directory, and if the last modified date of any blob is past 30 days from the current date, it will be deleted. A bit of overhead, but we can automate the clean up of `/objects/tmp` and prevent it from building up and taking up disk space.

**Comment by mbjones** [comment]
Maybe that would work, but it seems a bit late as a means of detection of a problem. Would be better to have a more proactive way of assessing whether the connection that was transferring a data object was lost, and therefore the temp file will never be completed? Maybe you could discuss architecturally with @taojing2002 and @artntek how we can reliably determine if a data transfer process was severed with the client, and then a proactive approach to cleaning temp when that happens.

**Comment by doulikecookiedough** [comment]
Sounds good and will do!

**Comment by doulikecookiedough** [comment]
I have added code to ensure that temporary files are cleaned up (removed from `/objects/tmp`) and executed the testing strategies described above. HashStore-Java appears to be working smoothly, but Python is not behaving consistently with a forceful termination.

**Java:**
- Whether I let the JVM finish on its own or forcefully terminate the process in the console (Ctrl + C) for the above testing strategies, redundant temporary files were deleted.

**Python:**
- Allowing the process to complete in all strategies will remove the temporary files as expected.
- However, a `KeyboardInterrupt` (forceful termination) can at times leave temp files behind.
    - It inconsistently leaves behind 2-10 files, based on the amount of processes run, and is not easily reproduce-able. Most of the time, all temporary files are removed/cleaned up.
    - This looks to be an expected/observed issue with Python (unpredictable outcomes with forced termination), as `atexit` and `finally` blocks are not always executed in fatal situations.
        - Specifically catching and handling `KeyboardInterrupt` exceptions did not change the results (and feels like it left more temporary files).
    - If the cleanup process must be absolute, it looks like a "monitor" or "watchdog" would be necessary to keep on top of processes. Managing and facilitating processes feels a bit out of scope of this library - so I am opting to skip exploration here unless we want to make it a requirement. 

Summary:
- The cleanup process is much more reliable in Java than in Python. Overall, the Public API calls in both Java/Python are behaving in an expected manner.

**Comment by mbjones** [comment]
Good summary.

For the Java process, if you do a `kill -9` on the command line for the JVM, do you still see clean removal of temp files? I'd be surprised if you do, as a `KILL` signal is much more immediate than a `SIGHUP`.  In both that case and the python case, it seems like the only alternative would be to properly handle cleanup as well on startup after a terminating event like this.

A couple of other things that you might want to carefully check:

1) What happens if the storage system disk hits 100% full in the middle of a store request?
2) what happens if the storage mount is removed in the middle of an operation (can simulate by forcefully unmounting a temporary filesystem.
3) what happens if, in a kubernetes deployment, the process is moved from one node to another on a new pod?
    - we can talk about how to test this one with @artntek -- it should be fairly easy to setup a temporary image to test this

**Comment by doulikecookiedough** [comment]
Thank you for the feedback @mbjones! You're right, when I do a `kill -9`, the temp files are not cleaned up. I'm currently in the process of answering the three questions raised and will update this issue once I've finished testing.

**Comment by doulikecookiedough** [comment]
Following up on points 1) and 2) raised above with a testing on a new image/volume that I mounted to my machine with a max capacity of 5GB:

**HashStore-Java:**
- When calling `store_object` to this volume that does not have enough space for additional objects, the exit/termination code & JVM works as expected and deletes the temporary files.
    - Every thread thereafter also encounters the same `IOException (No space left on device)`
- When forcefully unmounting the volume (`sudo diskutil unmount force /Volumes/5GB`) while `store_object` is in progress, the temporary files do not get removed and are left behind. 

**HashStore-Python:**
- When calling `store_object` to this volume that does not have enough space for additional objects, the exit/termination code executes and deletes the temporary files
    - `OSError (No space left on device)` is encountered for both threads and processes
    - All temporary files are cleaned up if Python Interpreter is not interrupted
- When forcefully unmounting the volume:
    - Threads:
        - `PermissionError: [Errno 13] Permission denied: '/Volumes/5GB'` errors are encountered and temp files are left behind.
    - Processes:
        - `OSErrors 'Input/output error'` are thrown followed by `PermissionErrors`. Temp files are left behind as well.
        
I will update this issue regarding Point #3 (what happens in kubernetes deployment) when I've made progress.

**Comment by doulikecookiedough** [comment]
**Update:**
- Testing with the latest storeObject refactor is ongoing in `knbvm` in both Java and Python libraries. 
- HashStore-java
    - Successfully stored the first 100000 records from `knbvm`'s metacat pgdb where the object actually exists in `var/metacat/data`.
        - However, when an object already exists when calling `storeObject` when a pid is available, I am currently rejecting the request rather than creating the pid reference file and updating the cid reference file. Need confirmation of the behaviour in this scenario.
    - Currently, all objects that exist in `var/metacat/data` are being stored
- HashStore (python) will be used to test the delete process (objects and reference files) once the Java process is completed to store all objects.
    - Afterwards, Python will be used to store all objects and Java will be used to delete objects.
- TODO: Execute the previous tests to confirm behaviour during race conditions

**Comment by doulikecookiedough** [comment]
**Update (after refactors to `delete_object` and clarifications to processes)**
- HashStore (python)
    - Successfully stored/deleted all data objects in `knbvm` that are <1gb
    - There are several data objects with multiple `pids`, updating and removing `pids` from the `cid refs file` is working as intended
    - Both `thread` and `multiprocessing` locks appear to be working as expected, and is executing efficiently with the usage of `Conditions` to help with synchronizing the process
- HashStore-java
    - Successfully stored/deleted all data objects in `knbvm` that are <1gb, reference files are updating as intended
    - When called to store 50 `pids` for 1 data object, then to delete the same 50 `pids` after - while another process adds another 50 `pids` to the same data object - the `cid reference file` is updated correctly with the right amount of values/`pids`
    - Parallelization with `ExecutorService` works well when running a `Runnable` class with a for loop as well as using the existing built in `.parallelStream.forEach()` on a list.
    
**TODO:**
- Test storing/deleting metadata in both libraries after new updates
- Store with java, delete with python library & vice versa

**Comment by doulikecookiedough** [comment]
**Update:**
- Storing/deleting objects & metadata with the python & the java library is behaving as expected
- Cross-language testing looks good with storing/deleting objects & metadata
- Testing continues as HashStore is integrated into Metacat

**Comment by doulikecookiedough** [comment]
HashStore and HashStore-java has been and continues to be tested - both libraries are on their way to their respective releases. Closing this issue and new issues will be created as bugs are discovered
