### ISSUE TITLE
Refactor 'store_sysmeta' to 'store_metadata'

### ISSUE THREAD

**Issue by doulikecookiedough** [DataONEorg/hashstore#35]
To account for additional metadata types (which are going to be needed immediately), we need to revise our current `store_sysmeta` Public API call to `store_metadata`.

**Rough Todo Outline:**
- Review initialization process:
    - Currently we create the `/objects` and `/sysmeta` directories after given properties
    - Do we go through properties to initialize the metadata directories, or perhaps allow `store_metadata` to dictate what gets created? If so, how do we ensure that innocent typos don't cause metadata to be stored in unintended directories (ex. `store_metadata(pid, "ssymeta"`)? Explore different paths to prevent confusion.
    - Perhaps we need to pre-define a list of accepted metadata types
         - How does this impact the 'hashstore.yaml' configuration process when the list changes?
- Review expected changes to existing sysmeta methods:
    - `store_sysmeta` --> `store_metadata`
    - `retrieve_sysmeta` --> `retrieve_metadata`
    - `delete_sysmeta` --> `delete_metadata`
    - Work with and add new argument `entity`, which represents the metadata type (ex. sysmeta, annotations)
 - Create mermaid diagrams to represent changes before coding

**Comment by mbjones** [comment]
> - Perhaps we need to pre-define a list of accepted metadata types

For sure. My initial inclination is that we should use our DataONE formatId vocabulary, but let's discuss. See the list at  https://cn.dataone.org/cn/v2/formats (and see https://github.com/DataONEorg/object-formats for proposing new format types).

**Comment by doulikecookiedough** [comment]
What do you think about using this formatted list below as the directory/folder for each metadata type? It's not very pretty, but it would be accurate. Calling app would provide the exact metadata format Id from DataONE, which I would map on my end to the folders above.
- **Usage:**
  ```
  store_metadata(pid, "http://purl.org/ornl/schema/mercury/terms/v1.0")
  ```

After parsing for the metadata formats, removing all special characters and `http`, `https`, `www` and calling `.lower()`, we end up with a list like this:
```
emlecoinformatics.orgeml2.0.0
emlecoinformatics.orgeml2.0.1
emlecoinformatics.orgeml2.1.0
emlecoinformatics.orgeml2.1.1
eml.ecoinformatics.orgeml2.2.0
esri.commetadataesriprof80.dtd
fgdcstd001.11999
fgdcstd001.21999
fgdcstd0011998
incits4532009
unidata.ucar.edunamespacesnetcdfncml2.2
loc.govmets
rs.tdwg.orgdwcxsdsimpledarwincore
digir.netschemaconceptualdarwin20031.0darwin2.xsd
datadryad.orgprofilev3.1
purl.orgdryadterms
ecoinformatics.orgemlaccess2.0.0beta4en
ecoinformatics.orgemlattribute2.0.0beta4en
ecoinformatics.orgemlconstraint2.0.0beta4en
ecoinformatics.orgemlcoverage2.0.0beta4en
ecoinformatics.orgemldataset2.0.0beta4en
ecoinformatics.orgemldistribution2.0.0beta4en
ecoinformatics.orgemlentity2.0.0beta4en
ecoinformatics.orgemlliterature2.0.0beta4en
ecoinformatics.orgemlparty2.0.0beta4en
ecoinformatics.orgemlphysical2.0.0beta4en
ecoinformatics.orgemlproject2.0.0beta4en
ecoinformatics.orgemlprotocol2.0.0beta4en
ecoinformatics.orgemlresource2.0.0beta4en
ecoinformatics.orgemlsoftware2.0.0beta4en
ecoinformatics.orgemlaccess2.0.0beta6en
ecoinformatics.orgemlattribute2.0.0beta6en
ecoinformatics.orgemlconstraint2.0.0beta6en
ecoinformatics.orgemlcoverage2.0.0beta6en
ecoinformatics.orgemldataset2.0.0beta6en
ecoinformatics.orgemldistribution2.0.0beta6en
ecoinformatics.orgemlentity2.0.0beta6en
ecoinformatics.orgemlliterature2.0.0beta6en
ecoinformatics.orgemlparty2.0.0beta6en
ecoinformatics.orgemlphysical2.0.0beta6en
ecoinformatics.orgemlproject2.0.0beta6en
ecoinformatics.orgemlprotocol2.0.0beta6en
ecoinformatics.orgemlresource2.0.0beta6en
ecoinformatics.orgemlsoftware2.0.0beta6en
ddicodebook25
icpsr.umich.eduddi
purl.orgornlschemamercurytermsv1.0
datacite.orgschemakernel3.0
datacite.orgschemakernel3.1
ns.dataone.orgmetadataschemaonedcxv1.0
isotc211.org2005gmd
isotc211.org2005gmdnoaa
isotc211.org2005gmdpangaea
openarchives.orgoai2.0oaidc
purl.dataone.orgcollections1.0.0
purl.dataone.orgportals1.0.0
purl.dataone.orgcollections1.1.0
purl.dataone.orgportals1.1.0
scienceonschema.orgdatasetldjson
```

**Script for reference if you want to play around:**
```
"""Script to retrieve and format a list of metadata from DataONE"""
import re
import requests
import xmltodict

METADATA_LIST_URL = "https://cn.dataone.org/cn/v2/formats"

response = requests.get(METADATA_LIST_URL, timeout=30)
if response.status_code == 200:
    # Access the content of the response
    metadata_xml = response.content
    metadata_dictionary = xmltodict.parse(metadata_xml)
    metadata_count= int(metadata_dictionary["ns3:objectFormatList"]["@total"])
    metadata_formats = metadata_dictionary["ns3:objectFormatList"]["objectFormat"]
    for i in range(0, metadata_count):
        if metadata_formats[i]["formatType"] == "METADATA":
            format_id = (
                metadata_formats[i]["formatId"]
                .replace("https", "")
                .replace("http", "")
                .replace("www.", "")
                .lower()
            )
            format_id_final = re.sub("[^a-zA-Z0-9 \n\.]", "", format_id)
            print(format_id_final)
```

**Comment by doulikecookiedough** [comment]
I **really** like this idea @mbjones.
- Regarding the `formatId` of the `hash(pid+formatId)`, I think we should also validate it against the list from `https://cn.dataone.org/cn/v2/formats` and use the value from the list if there is a match. 
    - This way, we can guarantee consistency of the `formatId` portion, and calculate the hex digest directly without cleaning up the `formatId` (which feels redundant and prone to errors).
    - If you agree, then my next thought is how we should obtain/maintain this list. Should it be added to the configuration file or on its own? My gut feeling is that it should be a separate file in the store directory (same level as `hashstore.yaml`) and it will be generated/updated upon FileHashStore initialization (ex. `metadatalist.yaml`)
- It also makes me happy that our `/metadata` objects will no longer share the same permanent address as the data files they represent.

If @artntek and @taojing2002 also agree, I will proceed as described and come back with any findings/issues.

**Comment by mbjones** [comment]
Hi @doulikecookiedough -- yeah, I think we should use the exact value of `formatId` from the [formats service](https://cn.dataone.org/cn/v2/formats), with no changes.  I don't think you need to store the list of formats -- they are already stored in the formats service. In many ways, hashstore may not care what the value is -- it would be up to the client to use the right value in their call.  So, imagine a client wants to store a CSV file named `lakedata.csv` with a PID of `pid1` and a formatId of `text/csv`. Then we would have something like:

- Data object stored with: store('pid1', data)
- Sysmeta stored with: store_metadata('pid1', 'http://ns.dataone.org/service/types/v2.0:SystemMetadata', metadata)
- JSON-LD annotations stored with: store_metadata('pid1', 'application/json-ld', metadata)

Does that seem right? We don't have an official formatId for sysmeta yet, so let's open an object-formats ticket to create that.

**Comment by doulikecookiedough** [comment]
That sounds good to me - I will open an object-format ticket for `sysmeta` after @artntek and @taojing2002 have had a chance to review this issue (or immediately if you prefer, please let me know).

**Comment by doulikecookiedough** [comment]
I created new ticket for `System Metadata (HashStore)` and filled out the details as best I can for now. As I get feedback/clarification, I will update the issue/description.
- https://github.com/DataONEorg/object-formats/issues/38

**Comment by doulikecookiedough** [comment]
**Summary of Changes To Do (confirm & discuss w/ team on Tuesday Backend Dev Meeting):**
1) Rename `sysmeta` directory to `metadata`, and update all references
2) Rename HashStore interface methods:
    - `store_sysmeta(pid, sysmeta)` -> `store_metadata(pid, formatId, metadata)`
    - `retrieve_sysmeta(pid)` -> `retrieve_metadata(pid)`
    - `delete_sysmeta(pid)` -> `delete_metadata(pid)`
    - Update [substorage document](https://github.com/NCEAS/metacat/blob/feature-1436-storage-and-indexing/docs/user/metacat/source/storage-subsystem.rst)
         - Note our discussion, and the requirement of a `formatId`, link this issue
         - HashStore is not responsible for ensuring the calling app provides the correct `formatId`
2) Refactor above Public API methods via `feature-35-store-metadata`

**Comment by doulikecookiedough** [comment]
Refactor is [complete](https://github.com/DataONEorg/hashstore/pull/37) and substorage document has been [updated](https://github.com/NCEAS/metacat/blob/feature-1436-storage-and-indexing/docs/user/metacat/source/storage-subsystem.rst).
